### ISSUE TITLE
Pouvoir ajouter une carte OSM avec un point de rendez-vous

### ISSUE THREAD

**Issue by AntoineTurmel** [leblanc-simon/OpenSondage#61]
Il serait bien de pouvoir ajouter des coordonnées pour donner un lieu précis d'un rendez-vous. L'affichage et choix du lieu pourrait se faire via un module OpenStreetMap.

**Comment by AntoineTurmel** [comment]
Pourquoi fermer le ticket ?

**Comment by leblanc-simon** [comment]
J'ai fermé l'ensemble des tickets car : 
* le projet n'a pas évolué depuis 5 ans
* le projet a été forké sur https://github.com/framasoft/framadate

Il est préférable de mettre les demandes directement sur Framadate
